In [1]:
%pwd

'/workspaces/Master-Degree-Research/notebooks'

In [13]:
import pandas as pd
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_absolute_percentage_error

import sys
sys.path.append("../src/")
from utils.evaluation import FI_shap_values

import pickle



In [3]:
%load_ext autoreload
%autoreload 2
%reload_ext autoreload

In [4]:
df_apol = pd.read_csv("../data/processed/processed_apolar.csv")
df_apol.head()

Molecule Formula    Ei  Alpha  Expt  pi_bond
0   Butane   C4H10  10.6    8.1    35        0
1  Pentane   C5H12  10.4   10.0    60        0
2   Hexane   C6H14  10.2   11.8    80        0
3  Heptane   C7H16   9.9   13.7   105        0
4   Octane   C8H18  10.0   15.5   115        0

# F.I para $\pi$ e $\alpha$

In [5]:
x = df_apol[['Alpha', 'pi_bond']].values
y = df_apol["Expt"].values

x.shape, y.shape

((20, 2), (20,))

In [6]:
all_models = pickle.load(open("../models/apolar/pi_alpha/all_molecules_models.sav", "rb"))
poli = all_models[0]
svr = all_models[1]
nn = all_models[3]

In [7]:
FI_shap_values(svr, x, y)

  0%|          | 0/20 [00:00<?, ?it/s]

[[-57.16640972 -16.26864081]
 [-37.32833531 -13.84348769]
 [-16.76701824 -11.93287539]
 [  4.86824316 -10.45350527]
 [ 24.62562294  -9.45782596]
 [ 45.06115148  -8.55223392]
 [108.5620106   -4.16808376]
 [178.50703336   3.79832377]
 [-64.12728889 -26.17948071]
 [-75.13470279 -19.36228245]
 [-16.76701824 -11.93287539]
 [-21.99666118  63.52279244]
 [ 34.33442171 155.34119099]
 [-40.97365935   7.64926602]
 [-37.32833531 -13.84348769]
 [151.18046862   0.35415173]
 [-71.6666525  -18.63159318]
 [-15.8023732  -37.53216279]
 [-53.22135116 -33.98575189]
 [-38.85914597   5.47856193]]
[54.71389519 23.61442869]


[0.6985199284168869, 0.301480071583113]

In [8]:
FI_shap_values(poli, x, y)

  0%|          | 0/20 [00:00<?, ?it/s]

[[-14.19346025 -25.93840473]
 [ -7.88963059 -28.39582642]
 [ -1.91758144 -30.72391013]
 [  4.38624822 -33.18133182]
 [ 10.35829737 -35.50941553]
 [ 16.66212703 -37.96683722]
 [ 34.91005499 -45.08042632]
 [ 59.46181261 -54.65143712]
 [-42.19215265   9.41785155]
 [-22.15619245 -22.83429312]
 [ -1.91758144 -30.72391013]
 [-19.66444631  94.09886635]
 [ 45.63101998 221.54764111]
 [-30.18413329  48.35245871]
 [ -7.88963059 -28.39582642]
 [ 47.1859338  -49.86593172]
 [-20.1655094  -23.61032103]
 [ -1.34942923  12.90997711]
 [-22.27502209  11.12080167]
 [-26.80072429  49.43027524]]
[21.8595494  44.68778717]


[0.3284812063901753, 0.6715187936098246]

In [9]:
FI_shap_values(nn, x, y)

  0%|          | 0/20 [00:00<?, ?it/s]

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[0. 0.]


invalid value encountered in divide


[nan, nan]

In [10]:
nn

TransformedTargetRegressor(regressor=Pipeline(steps=[('scale',
                                                      ColumnTransformer(remainder='passthrough',
                                                                        transformers=[('scale',
                                                                                       MinMaxScaler(),
                                                                                       slice(0, -1, None))])),
                                                     ('reg',
                                                      MLPRegressor(beta_1=0.8195079385558488,
                                                                   beta_2=0.8990920653480827,
                                                                   epsilon=9.979001956130388e-06,
                                                                   hidden_layer_sizes=(3,
                                                                                       3,
                                                                                       3,
                                                                                       3,
                                                                                       3,
                                                                                       3,
                                                                                       3,
                                                                                       3),
                                                                   learning_rate_init=1.0901976576015944e-06,
                                                                   max_iter=5000,
                                                                   random_state=0))]),
                           transformer=MinMaxScaler())

In [25]:
nn.set_params(regressor__reg__random_state = None)

TransformedTargetRegressor(regressor=Pipeline(steps=[('scale',
                                                      ColumnTransformer(remainder='passthrough',
                                                                        transformers=[('scale',
                                                                                       MinMaxScaler(),
                                                                                       slice(0, -1, None))])),
                                                     ('reg',
                                                      MLPRegressor(beta_1=0.8195079385558488,
                                                                   beta_2=0.8990920653480827,
                                                                   epsilon=9.979001956130388e-06,
                                                                   hidden_layer_sizes=(3,
                                                                                       3,
                                                                                       3,
                                                                                       3,
                                                                                       3,
                                                                                       3,
                                                                                       3,
                                                                                       3),
                                                                   learning_rate_init=1.0901976576015944e-06,
                                                                   max_iter=5000))]),
                           transformer=MinMaxScaler())

In [33]:
nn.fit(x, y)

nn_preds = nn.predict(x)
nn_preds

array([-72.96372527, -72.96372527, -72.96372527, -72.96372527,
       -72.96372527, -72.96372527, -72.96372527, -72.96372527,
       -72.96372527, -72.96372527, -72.96372527, -72.96372527,
       -72.96372527, -72.96372527, -72.96372527, -72.96372527,
       -72.96372527, -72.96372527, -72.96372527, -72.96372527])

In [14]:
mean_absolute_percentage_error(y, nn_preds)

0.7514530279363919

In [34]:
from sklearn.model_selection import cross_val_score
import numpy as np

scores = -cross_val_score(nn, x, y, cv = len(x), scoring = "neg_mean_absolute_percentage_error")

scores

array([11.70996338,  4.03221594,  3.6601531 ,  0.53151889,  0.04043793,
        0.37312473,  3.53225805,  0.61016518, 15.75364732, 37.87648178,
        2.83996656,  1.32978354,  0.44734211,  2.64035731,  1.58897467,
        0.93547213,  9.30123786, 12.64174007, 34.26738024,  2.36531369])

In [35]:
np.mean(scores), np.std(scores)

(7.32387672260049, 10.57509592724391)